# Author queries and mutations

extend type Query {
    # Fetches all authors
    authors: [Author!]
}

# Author type definition
type Author {
    id: ID
    firstName: String
    lastName: String
}

# Input type for author creation and updates
input AuthorInput {
    firstName: String!
    lastName: String!
}

extend type Mutation {
    # Creates a new author
    createAuthor(author: AuthorInput!): Author!
    
    # Updates an existing author by ID
    updateAuthor(id: ID!, author: AuthorInput!): Author!
    
    # Deletes an author by ID
    deleteAuthor(id: ID!): ID!
}