# This file extends the root 'Query' type to add book-related queries
# and defines the 'Book' type structure.

# 'extend type Query' means we are adding new fields to the existing Query type
# defined in schema.graphqls.
extend type Query {
    # 'books' is a query field that returns a list of 'Book' objects.
    # The '!' indicates that the list itself cannot be null, and the items
    # within the list also cannot be null.
    books: [Book!]

    # 'bookById' is a query field that returns a single 'Book' object.
    # It takes one argument:
    # - 'id': The ID of the book to retrieve. The 'ID!' indicates it's a non-nullable ID.
    bookById(id: ID!): Book

    # 'booksByAuthor' is a query field that returns a list of 'Book' objects
    # written by a specific author.
    # It takes one argument:
    # - 'id': The ID of the author whose books to retrieve. The 'ID!' indicates it's a non-nullable ID.
    booksByAuthor(id: ID!): [Book!]
}

# The 'Book' type defines the structure of a Book object in our GraphQL API.
type Book {
    # 'id' is a unique identifier for the book. 'ID' is a built-in GraphQL scalar type.
    id: ID
    # 'name' is the title of the book, a String.
    name: String
    # 'pageCount' is the number of pages in the book, an Integer.
    pageCount: Int
    # 'author' is a field that represents the author of the book.
    # It establishes a relationship with the 'Author' type.
    author: Author
}