# This file extends the root 'Query' type to add book-related queries
# and defines the 'Book' type structure.

# 'extend type Query' means we are adding new fields to the existing Query type
# defined in schema.graphqls.
extend type Query {
    # 'books' is a query field that returns a list of 'Book' objects.
    # The '!' indicates that the list itself cannot be null, and the items
    # within the list also cannot be null.
    books: [Book!]

    # 'bookById' is a query field that returns a single 'Book' object.
    # It takes one argument:
    # - 'id': The ID of the book to retrieve. The 'ID!' indicates it's a non-nullable ID.
    bookById(id: ID!): Book

    # 'booksByAuthor' is a query field that returns a list of 'Book' objects
    # written by a specific author.
    # It takes one argument:
    # - 'id': The ID of the author whose books to retrieve. The 'ID!' indicates it's a non-nullable ID.
    booksByAuthor(id: ID!): [Book!]

    booksWithFilter(
        id: ID
        authorId: ID
        name: String
    ): [Book!]
}

type Book {
    id: ID
    name: String
    pageCount: Int
    author: Author
}

input BookInput {
    name: String!
    pageCount: Int!
    authorId: ID!
}

extend type Mutation {
    createBook(book: BookInput!): Book!
    updateBook(id: ID, book: BookInput): Book!
    deleteBook(id: ID!): ID!
}